services:
  - type: web
    name: estatias-host-service
    env: node
    buildCommand: cd backendd/services/host-service && npm install --include=dev && npm run build
    startCommand: cd backendd/services/host-service && npm run start:prod
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003