services:
  - type: web
    name: estatias-api-gateway
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    plan: free
    region: frankfurt
    branch: main
    rootDir: backendd/services/api-gateway
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000