services:
  - type: web
    name: estatias-api-gateway
    env: node
    buildCommand: cd backendd/services/api-gateway && npm install && npm run build
    startCommand: cd backendd/services/api-gateway && npm run start:prod
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000