export const nationalIdPatterns: Record<string, RegExp> = {
    'AR': /^\d{8}$/, // Argentina (DNI - 8 digits)
  'AU': /^\d{9}$/, // Australia (TFN - 9 digits)
  'BE': /^\d{11}$/, // Belgium (11 digits)
  'BR': /^\d{11}$/, // Brazil (CPF - 11 digits)
  'CA': /^\d{9}$/, // Canada (SIN - 9 digits)
  'CN': /^\d{15}|\d{18}$/, // China (15 or 18 digits)
  'DE': /^\d{11}$/, // Germany (Tax ID - 11 digits)
  'DK': /^\d{10}$/, // Denmark (CPR - 10 digits)
  'ES': /^[0-9]{8}[A-Z]$/, // Spain (DNI - 8 digits + 1 letter)
  'FI': /^\d{6}[-+A]\d{3}[0-9A-FHJ-NPR-Y]$/, // Finland (Henkilötunnus)
  'FR': /^\d{13}$/, // France (INSEE - 13 digits)
  'GB': /^[A-CEGHJ-NOPRTUW-Z]{2}\d{6}[A-D\s]?$/, // UK (NIN - 2 letters, 6 digits, optional letter)
  'IN': /^\d{12}$/, // India (Aadhaar - 12 digits)
  'IT': /^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$/, // Italy (Codice Fiscale)
  'JP': /^\d{12}$/, // Japan (My Number - 12 digits)
  'MX': /^[A-Z]{4}\d{6}[A-Z0-9]{3}$/, // Mexico (CURP)
  'NL': /^\d{9}$/, // Netherlands (BSN - 9 digits)
  'NO': /^\d{11}$/, // Norway (Fødselsnummer - 11 digits)
  'PL': /^\d{11}$/, // Poland (PESEL - 11 digits)
  'PT': /^\d{9}$/, // Portugal (NIF - 9 digits)
  'RO': /^\d{13}$/, // Romania (CNP - 13 digits)
  'RU': /^\d{12}$/, // Russia (SNILS - 12 digits)
  'SE': /^\d{10}$/, // Sweden (Personnummer - 10 digits)
  'TR': /^\d{11}$/, // Turkey (T.C. Kimlik No - 11 digits)
  'US': /^\d{3}-\d{2}-\d{4}$/ // United States (SSN - 3-2-4 format)
};